// <auto-generated />
using BrainenceCore_Task.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BrainenceCore_Task.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190126210708_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BrainenceCore_Task.Models.Sentences", b =>
                {
                    b.Property<string>("text")
                        .ValueGeneratedOnAdd();

                    b.HasKey("text");

                    b.ToTable("Text");
                });
#pragma warning restore 612, 618
        }
    }
}
